### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by jamesyyq27** [Ivannnmmn/esx_wanted#1]
[ERROR] [MySQL] [esx_wanted] An error happens on MySQL for query "SELECT wanted FROM users WHERE identifier = 'steam:11000010ffe3090'": ER_BAD_FIELD_ERROR: Unknown column 'wanted' in 'field list'
SCRIPT ERROR: @esx_wanted/server/main.lua:94: attempt to index a nil value (local 'result')

**Comment by ashton1cav** [comment]
Edit lines 104 to 121 in server\main.lua to look like this..

ESX.RegisterServerCallback("esx_wanted:retrieveWantedPlayers", function(source, cb)
	
	local wantedPersons = {}

    MySQL.Async.fetchAll("SELECT firstname, lastname, wanted, identifier FROM users WHERE wanted > @wanted", { ["@wanted"] = 0 }, function(result)


        for i = 1, #result, 1 do
            table.insert(wantedPersons, { 
                name = result[i].firstname,
                wantedTime = result[i].wanted,
                identifier = result[i].identifier,
            })
		end

		cb(wantedPersons)
	end)
end)

**Comment by Ivannnmmn** [comment]
I have updated, if there are other questions, please ask thank you.
